---
cidr_networks:
  container: 172.31.16.0/22
  tunnel: 172.31.20.0/22
  storage: 172.31.24.0/22

used_ips:
  - "172.31.16.20,172.31.16.250"
  - "172.31.17.20,172.31.17.250"
  - "172.31.18.20,172.31.18.250"
  - "172.31.19.20,172.31.19.250"
  - "172.31.20.1,172.31.20.250"
  - "172.31.21.1,172.31.21.250"
  - "172.31.22.1,172.31.22.250"
  - "172.31.23.1,172.31.23.250"
  - "172.31.24.1,172.31.24.250"
  - "172.31.25.1,172.31.25.250"
  - "172.31.26.1,172.31.26.250"
  - "172.31.27.1,172.31.27.250"

global_overrides:
  internal_lb_vip_address: 172.31.16.11
  external_lb_vip_address: 52.53.112.75
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "eth12"
        type: "flat"
        net_name: "flat"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "1:1"
        net_name: "vlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute

###
### Infrastructure
###

# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  infra1:
    ip: 172.31.16.11

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  infra1:
    ip: 172.31.16.11

# load balancer
haproxy_hosts:
  infra1:
    ip: 172.31.16.11

###
### OpenStack
###

# keystone
identity_hosts:
  infra1:
    ip: 172.31.16.11

# cinder api services
storage-infra_hosts:
  infra1:
    ip: 172.31.16.11

# glance
image_hosts:
  infra1:
    ip: 172.31.16.11

# nova api, conductor, etc services
compute-infra_hosts:
  infra1:
    ip: 172.31.16.11

# heat
orchestration_hosts:
  infra1:
    ip: 172.31.16.11

# horizon
dashboard_hosts:
  infra1:
    ip: 172.31.16.11

# neutron server, agents (L3, etc)
network_hosts:
  infra1:
    ip: 172.31.16.11

# nova hypervisors
compute_hosts:
  compute1:
    ip: 52.53.118.232

# cinder storage host (LVM-backed)
storage_hosts:
  storage1:
    ip: 13.56.33.7
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "172.31.19.11"

